import { fmtDate } from './format';

/** Document header: company identity left, report metadata right.
 *  Plain, divider below — per spec, no banners or color blocks. */
export function ReportHeader({ title, reportId, generatedBy }:
  { title: string; reportId: string; generatedBy?: string | null }) {
  return (
    <header className="rpt-header">
      <div className="rpt-header-row">
        <div className="rpt-company">
          <img src="/apple-touch-icon.png" alt="" className="rpt-logo" />
          <div>
            <div className="rpt-company-name">Pro Roto, Inc.</div>
            <div className="rpt-company-line">(650) 338-8332</div>
            <div className="rpt-company-line">workorders.proroto.com</div>
          </div>
        </div>
        <div className="rpt-meta">
          <div className="rpt-title">{title}</div>
          <div className="rpt-meta-line"><span>Report ID:</span> {reportId}</div>
          <div className="rpt-meta-line"><span>Generated:</span> {fmtDate()}</div>
          {generatedBy && <div className="rpt-meta-line"><span>Generated by:</span> {generatedBy}</div>}
        </div>
      </div>
      <hr className="rpt-rule" />
    </header>
  );
}
